// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CurrencyFormatterJs = require("./CurrencyFormatter.js").default;

var make = CurrencyFormatterJs;

exports.make = make;
/* make Not a pure module */
